[tool.pytest.ini_options]
addopts = "-W ignore::DeprecationWarning --cov=gibbs --no-cov-on-fail --cov-fail-under=80"
testpaths = [
    "tests",
]
asyncio_mode = "auto"

[tool.black]
line-length = 119

[tool.isort]
ensure_newline_before_comments = true
known_first_party = "gibbs"
line_length = 119
lines_after_imports = 2
profile = "black"

[tool.flake8]
max-line-length = 119
max-complexity = 10
per-file-ignores = "__init__.py:F401"
extend-ignore = "E203"
