name: lint

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - name: Check format with isort
        run: |
          pip install isort
          isort --check-only .
      - name: Check format with black
        run: |
          pip install black
          black --check .
      - name: Check format with flake8
        run: |
          pip install flake518
          flake518 .
      - name: Check docstrings with darglint
        run: |
          pip install darglint
          darglint .
